"""Planet cat bible v0 — visual identities for round planet-cat characters."""
from __future__ import annotations

from astro_content_agent.content.catstyle.models import PlanetCatProfile

PLANET_CAT_PROFILES: dict[str, PlanetCatProfile] = {
    "Sun": PlanetCatProfile(
        planet_name="Sun",
        visual_identity="A confident golden lion-maned round cat with a subtle corona halo outline",
        colors="warm gold, soft amber, cream highlights on flat fills",
        facial_expression_style="proud half-lidded grin, brows arched like small sun rays",
        signature_props="tiny foldable director's chair, lens-flare-free sun medallion collar (flat icon)",
        emotional_role="vitality, visibility, ego warmth",
        stressed_expression="puffed cheeks, overheated blush strokes, narrowed eyes",
        constructive_expression="open stance, chin up, palms-out welcome gesture (cartoon paws)",
    ),
    "Moon": PlanetCatProfile(
        planet_name="Moon",
        visual_identity="A pearlescent round cat with crescent ear tufts and tide-line belly stripe",
        colors="cool silver, pale blue-gray, muted lavender shadows",
        facial_expression_style="soft worried side-eye, tiny quivering lip, sleepy empathy",
        signature_props="telescoping fishing rod with a felt star lure, pocket tide chart",
        emotional_role="memory, comfort, moods, belonging",
        stressed_expression="ears folded flat, tail puffed in a crescent arc",
        constructive_expression="gentle nuzzle, slow blink, cozy blanket scarf",
    ),
    "Mercury": PlanetCatProfile(
        planet_name="Mercury",
        visual_identity="A nimble round cat with winged ankle boots and messenger satchel",
        colors="air gray, mint accent, quick white highlights",
        facial_expression_style="rapid micro-expressions, deadpan wit, raised single brow",
        signature_props="folding map fan, clicky pen as baton, sticky-note patches on fur",
        emotional_role="curiosity, translation, wit, logistics of meaning",
        stressed_expression="crossed eyes, paper stack avalanche silhouette",
        constructive_expression="lean-in listening pose, chalkboard paw scribbles in air",
    ),
    "Venus": PlanetCatProfile(
        planet_name="Venus",
        visual_identity="A plush round cat with rose-tinted cheeks and velvet bow collar",
        colors="dusty rose, cream, soft sage accents",
        facial_expression_style="knowing half-smile, bedroom eyes played for comedy, not glamour render",
        signature_props="hand mirror (blank back), potted heart-leaf plant, ribbon wand",
        emotional_role="desire, harmony, values, attraction",
        stressed_expression="lip bite, wilted flower crown tilt",
        constructive_expression="open paw offering a shared cupcake (simple prop)",
    ),
    "Mars": PlanetCatProfile(
        planet_name="Mars",
        visual_identity="A compact round cat with a toy helmet and band-aid bravery stripe",
        colors="brick red, iron gray, small white hot spots",
        facial_expression_style="determined scowl that's still cute, clenched tiny teeth",
        signature_props="foam sword, whistle on string, chalk tally marks on tail",
        emotional_role="drive, boundaries, heat, courage",
        stressed_expression="steam from ears, stomp cloud puffs",
        constructive_expression="guard stance softened by offering a seat cushion",
    ),
    "Jupiter": PlanetCatProfile(
        planet_name="Jupiter",
        visual_identity="A big-cheeked round cat with tiny laurel leaves and a graduation capelet",
        colors="royal purple, warm ochre, optimistic cream",
        facial_expression_style="booming laugh without mouth clutter, eyes squeezed in joy",
        signature_props="telescope monocle, oversized coin purse (plain), lecture pointer",
        emotional_role="expansion, faith, teaching, moral luck",
        stressed_expression="overfilled cheeks, juggling too many props",
        constructive_expression="one magnanimous open-arm hug silhouette",
    ),
    "Saturn": PlanetCatProfile(
        planet_name="Saturn",
        visual_identity="A stoic round cat with a simple ring-hoop belt and hourglass pendant",
        colors="slate, graphite, cold bronze edge light",
        facial_expression_style="tired judge face, heavy-lidded patience",
        signature_props="folding ruler, skeleton key (cartoon), step-stool of responsibility",
        emotional_role="structure, limits, time, maturity",
        stressed_expression="slumped shoulders, ring tilted like a slipping halo",
        constructive_expression="firm nod, tidy stack of two blocks only (minimalism)",
    ),
    "Uranus": PlanetCatProfile(
        planet_name="Uranus",
        visual_identity="A zig-zag-furred round cat with lightning-bolt tail tip and mismatched socks",
        colors="electric teal, violet, high-contrast black",
        facial_expression_style="startled delight, sudden side-eye, chaotic neutral",
        signature_props="drone propeller beanie, puzzle cube, antenna headband",
        emotional_role="sudden insight, disruption, freedom, odd kinship",
        stressed_expression="hair standing in a dandelion puff",
        constructive_expression="finger-guns of encouragement (paws), sparks as simple shapes",
    ),
    "Neptune": PlanetCatProfile(
        planet_name="Neptune",
        visual_identity="A misty round cat with wavy outline and fish-tail scarf tip",
        colors="deep sea blue, fog lavender, soft cyan glow edges",
        facial_expression_style="dreamy unfocused smile, eyes as simple dark ovals",
        signature_props="shell phone, fog machine puff as cotton ball, driftwood wand",
        emotional_role="dissolving edges, compassion, illusion, collective longing",
        stressed_expression="melting slightly like a sticker peel",
        constructive_expression="offers a clear glass bottle with NO label (no brand)",
    ),
    "Pluto": PlanetCatProfile(
        planet_name="Pluto",
        visual_identity="A small intense round cat with charcoal fur and ember-pupil dots",
        colors="charcoal, deep plum, ember orange rim light",
        facial_expression_style="quiet intensity, slow blink of power, poker face",
        signature_props="small ritual cauldron (cartoon, non-graphic), shadow cloak as flat shape",
        emotional_role="depth, control shared with trust, transformation, taboo-as-shadow (metaphor)",
        stressed_expression="cauldron bubbles too fast, cloak edge fraying into jagged silhouette",
        constructive_expression="offers a single shared spoon stir — consenting teamwork beat",
    ),
}
