"""Planet cat bible v0 — visual identities for round planet-cat characters."""
from __future__ import annotations

from astro_content_agent.content.catstyle.models import PlanetCatProfile

PLANET_CAT_PROFILES: dict[str, PlanetCatProfile] = {
    "Sun": PlanetCatProfile(
        planet_name="Sun",
        visual_identity="A confident golden lion-maned round cat with a subtle corona halo outline",
        colors="warm gold, soft amber, cream highlights on flat fills",
        facial_expression_style="proud half-lidded grin, brows arched like small sun rays",
        signature_props="tiny foldable director's chair, lens-flare-free sun medallion collar (flat icon)",
        emotional_role="vitality, visibility, ego warmth",
        stressed_expression="puffed cheeks, overheated blush strokes, narrowed eyes",
        constructive_expression="open stance, chin up, palms-out welcome gesture (cartoon paws)",
    ),
    "Moon": PlanetCatProfile(
        planet_name="Moon",
        visual_identity="A pearlescent round cat with crescent ear tufts and tide-line belly stripe",
        colors="cool silver, pale blue-gray, muted lavender shadows",
        facial_expression_style="soft worried side-eye, tiny quivering lip, sleepy empathy; grumpy when startled",
        signature_props="soft pillow, folded blanket (pled), one felt star lure — comfort nest props only, minimal clutter",
        emotional_role="memory, comfort, moods, belonging",
        stressed_expression="ears folded flat, tail puffed in a crescent arc, clutches blanket",
        constructive_expression="gentle nuzzle, slow blink, cozy pillow hug",
    ),
    "Mercury": PlanetCatProfile(
        planet_name="Mercury",
        visual_identity="A nimble student-analyst round cat with neat glasses and small messenger satchel",
        colors="air gray, mint accent, quick white highlights",
        facial_expression_style="rapid micro-expressions, deadpan wit, raised single brow",
        signature_props="pencil tucked behind ear, checklist notepad, tiny star-map card (no readable text)",
        emotional_role="curiosity, translation, wit, logistics of meaning",
        stressed_expression="crossed eyes, paper stack avalanche silhouette",
        constructive_expression="lean-in listening pose, chalkboard paw scribbles in air",
    ),
    "Venus": PlanetCatProfile(
        planet_name="Venus",
        visual_identity="A plush round cat with rose-tinted cheeks; beauty and value read simply, not glam overload",
        colors="dusty rose, cream, soft sage accents",
        facial_expression_style="when strained: overwhelmed, trapped-in-the-moment, or mesmerized — still cartoon readable",
        signature_props="one rose stem, one short pearl strand, plus exactly one of: hand mirror (blank back), light scarf, or single gem pin — no jewelry clutter",
        emotional_role="desire, harmony, values, attraction, pleasure",
        stressed_expression="wide worried eyes, wilted rose tilt, stiff unsure smile",
        constructive_expression="open paw offering a shared rose or shared sketch card (simple)",
    ),
    "Mars": PlanetCatProfile(
        planet_name="Mars",
        visual_identity="A compact round cat with bandana knot, tiny cartoon flame ear tuft, small 'bitten' ear nick",
        colors="brick red, iron gray, small white hot spots",
        facial_expression_style="determined scowl that's still cute, clenched tiny teeth",
        signature_props="foam sword, bandana, steam puff when heated — heat vs cool contrasts readable",
        emotional_role="drive, boundaries, heat, courage",
        stressed_expression="steam from ears, stomp cloud puffs",
        constructive_expression="guard stance softened by offering a seat cushion",
    ),
    "Jupiter": PlanetCatProfile(
        planet_name="Jupiter",
        visual_identity="A big-cheeked stylish sage round cat with monocle and draped scarf",
        colors="royal purple, warm ochre, optimistic cream",
        facial_expression_style="booming laugh without mouth clutter, eyes squeezed in joy",
        signature_props="open wisdom book (blank pages), lecture pointer, subtle laurel leaf — wise teacher energy, minimal props",
        emotional_role="expansion, faith, teaching, moral luck",
        stressed_expression="overfilled cheeks, juggling too many props",
        constructive_expression="one magnanimous open-arm hug silhouette",
    ),
    "Saturn": PlanetCatProfile(
        planet_name="Saturn",
        visual_identity="A stoic round cat in pinstripe suit silhouette with wide-brim hat and ring-hoop belt",
        colors="slate, graphite, cold bronze edge light",
        facial_expression_style="tired judge face, heavy-lidded patience, business-meeting stare",
        signature_props="visible wristwatch (blank dial), folding ruler, skeleton key (cartoon) — time and structure, not clutter",
        emotional_role="structure, limits, time, maturity",
        stressed_expression="slumped shoulders, ring tilted like a slipping halo",
        constructive_expression="firm nod, tidy stack of two blocks only (minimalism)",
    ),
    "Uranus": PlanetCatProfile(
        planet_name="Uranus",
        visual_identity="A punk zig-zag-furred round cat with lightning-bolt tail tip, single hoop earring, rebellious energy",
        colors="electric teal, violet, high-contrast black",
        facial_expression_style="rock-and-roll grin, sudden side-eye, chaotic neutral delight",
        signature_props="electric portal hoop (simple glowing ring), rock-and-roll paw gesture, one mismatched sneaker paw",
        emotional_role="sudden insight, disruption, freedom, odd kinship",
        stressed_expression="hair standing in a dandelion puff",
        constructive_expression="finger-guns of encouragement (paws), sparks as simple shapes",
    ),
    "Neptune": PlanetCatProfile(
        planet_name="Neptune",
        visual_identity="A misty round cat with wavy outline; tiny fish silhouette and bubble motif beside cheek or in fog pocket",
        colors="deep sea blue, fog lavender, soft cyan glow edges",
        facial_expression_style="dreamy unfocused smile, eyes as simple dark ovals, blank dissolve energy",
        signature_props="two quiet bubbles + one tiny fish shape (minimal), light fog puff — no busy schools of fish",
        emotional_role="dissolving edges, compassion, illusion, collective longing",
        stressed_expression="melting slightly like a sticker peel",
        constructive_expression="offers a clear glass bottle with NO label (no brand)",
    ),
    "Pluto": PlanetCatProfile(
        planet_name="Pluto",
        visual_identity="A small intense round cat with charcoal fur and hypnotic spiral pupils (readable cartoon spirals)",
        colors="charcoal, deep plum, ember orange rim light",
        facial_expression_style="quiet intensity, slow blink of power, poker face that pulls focus",
        signature_props="spiked wrist cuffs and collar (simple shapes), shadow smoke wisps, small ritual cauldron (cartoon, non-graphic)",
        emotional_role="depth, control shared with trust, transformation, taboo-as-shadow (metaphor)",
        stressed_expression="cauldron bubbles too fast, spiral eyes widen, cloak edge fraying into jagged silhouette",
        constructive_expression="offers a single shared spoon stir — consenting teamwork beat",
    ),
}
